config/routes.rb
Rails.application.routes.draw do

  root 'tags#index'

  resources :authors
  resources :poems
  resources :short_stories
  resources :tags

end

app/models/poem.rb
# == Schema Information
#
# Table name: poems
#
#  id           :integer          not null, primary key
#  author_id    :integer
#  title        :string
#  metaphor     :text
#  content      :text
#  published    :boolean
#  publish_date :datetime
#  created_at   :datetime
#  updated_at   :datetime
#

class Poem < ActiveRecord::Base
  include Tags

  belongs_to :author
  has_many   :tag_connections, class_name: 'TagPoem', dependent: :destroy
  has_many   :tags, through: :tag_connections, source: :tag

  validates :author_id, :title, :metaphor, :content, presence: true
  validates :metaphor, length: { maximum: 1000 }
  validates :content,  length: { maximum: 5000 }

  scope :by_tag_title, -> (tag_title) { joins(tag_connections: :tag).where(tags: {title: tag_title}) }

  after_save :update_tags, :update_publish_date

  TAG_TYPES = ["title", "metaphor", "content"]

  def publish!
    self.published = true
    self.save
  end

  def unpublish!
    self.published = false
    self.save
  end

  def published?
    published
  end

  def tag_service
    @tag_service ||= TagService.new(self, TAG_TYPES)
  end

  def update_tags
    TaggingService.new(self, TAG_TYPES).tag_content
  end

  def update_publish_date
    if published_changed? && published
      update_column(:publish_date, DateTime.now)
    end
  end

end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController

  before_action :set_poem, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

  def index
    tag_title = params[:tag_title]
    @poems = Poem.all
    @poems = @poems.by_tag_title(tag_title) if tag_title.present?
  end

  def show
  end

  def new
    @poem = Poem.new
  end

  def create
    @poem = Poem.new(poem_params)
    if @poem.save
      redirect_to poem_path(@poem)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @poem.update(poem_params)
      redirect_to poem_path(@poem)
    else
      render :edit
    end
  end

  def destroy
    @poem.destroy
    redirect_to poems_path
  end

  def publish
    @poem.publish!
    redirect_to poem_path(@poem)
  end

  def unpublish
    @poem.unpublish!
    redirect_to poem_path(@poem)
  end

  private

  def set_poem
    @poem = Poem.find(params[:id])
  end

  def poem_params
    params.require(:poem).permit(:id, :author_id, :published, :title, :metaphor, :content)
  end

end

app/views/poems/_form.html.erb
<%= simple_form_for @poem do |f| %>

  <h4>Author</h4>

  <div class="row">
    <div class="col-xs-12">
      <%= f.association :author, as: :select, label: false, include_blank: 'Select author' %>
    </div>
  </div>

  <h4>Title</h4>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :title, label: false %>
    </div>
  </div>

  <h4>Metaphor</h4>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :metaphor, label: false %>
    </div>
  </div>

  <h4>Content</h4>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :content, label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :published %>
    </div>
  </div>
  <br><br>

  <div class="row">
    <div class="col-xs-12">
    <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/poems/edit.html.erb
<%= render partial: 'form' %>

app/views/poems/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= link_to 'New', new_poem_path %>
  </div>
</div>

<table class="table table-hover">
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Metaphor</th>
    <th>Content</th>
    <th>Published?</th>
    <th>Publish date</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @poems.each do |poem| %>
    <tr>
      <td><%= poem.author ? link_to(poem.author.name, poem_path(poem.author)) : 'Unknown author' %></td>
      <td><%= truncate(poem.title, length: 35) %></td>
      <td><%= truncate(poem.metaphor, length: 65) %></td>
      <td><%= truncate(poem.content, length: 65) %></td>
      <td><%= poem.published? ? 'Yes' : 'No' %></td>
      <td><%= poem.publish_date %></td>
      <td><%= link_to 'Show', poem_path(poem) %></td>
      <td><%= link_to 'Edit', edit_poem_path(poem) %></td>
      <td><%= link_to 'Delete', poem_path(poem), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/poems/new.html.erb
<%= render partial: 'form' %>

app/views/poems/show.html.erb
<h4>Author name</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @poem.author.present? ? @poem.author.name : 'Unknown author' %>
  </div>
</div>

<h4>Title</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @poem.title %>
  </div>
</div>

<h4>Metaphor</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @poem.metaphor %>
  </div>
</div>

<h4>Content</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @poem.content %>
  </div>
</div>

<h4>Published?</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @poem.published? ? 'Yes' : 'No' %>
  </div>
</div>

<% if @poem.published? %>
  <h4>Publish date</h4>
  <div class="row">
    <div class="col-xs-12">
      <%= @poem.publish_date %>
    </div>
  </div>
<% end %>

<h4>Tags</h4>
<%= render partial: 'tags/object_tags', locals: { target_object: @poem, helper_path: "poems_path" } %>