config/routes.rb
Rails.application.routes.draw do

  root 'tags#index'

  resources :authors
  resources :poems
  resources :short_stories
  resources :tags

end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  name       :string
#  biography  :text
#  created_at :datetime
#  updated_at :datetime
#

class Author < ActiveRecord::Base
  include Tags

  has_many :short_stories
  has_many :poems
  has_many :tag_connections, class_name: "TagAuthor", dependent: :destroy
  has_many :tags, through: :tag_connections, source: :tag

  validates :name, :biography, presence: true
  validates :biography, length: { maximum: 2500 }

  scope :by_tag_title, -> (tag_title) { joins(tag_connections: :tag).where(tags: {title: tag_title}) }

  after_save :update_tags

  TAG_TYPES = ["biography"]

  def tag_service
    @tag_service ||= TagService.new(self, TAG_TYPES)
  end

  def update_tags
    TaggingService.new(self, TAG_TYPES).tag_content
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    tag_title = params[:tag_title]
    @authors = Author.all
    @authors = @authors.by_tag_title(tag_title) if tag_title.present?
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to author_path(@author)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      redirect_to author_path(@author)
    else
      render :edit
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_path
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:id, :name, :biography)
  end

end

app/views/authors/_form.html.erb
<%= simple_form_for @author do |f| %>

  <h4>Name</h4>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :name, label: false %>
    </div>
  </div>

  <h4>Biography</h4>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :biography, label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
    <%= f.button :submit %>
    </div>
  </div>
  
<% end %>

app/views/authors/edit.html.erb
<%= render partial: "form" %>

app/views/authors/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= link_to 'New', new_author_path %>
  </div>
</div>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Biography</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.name %></td>
      <td><%= truncate(author.biography, length: 150) %></td>
      <td><%= link_to 'Show', author_path(author) %></td>
      <td><%= link_to 'Edit', edit_author_path(author) %></td>
      <td><%= link_to 'Delete', author_path(author), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/authors/new.html.erb
<%= render partial: "form" %>

app/views/authors/show.html.erb
<h4>Name</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @author.name %>
  </div>
</div>

<h4>Biography</h4>

<div class="row">
  <div class="col-xs-12">
    <%= @author.biography %>
  </div>
</div>

<h4>Poems</h4>

<% if @author.poems.count == 0 %>
  0 poems
<% else %>
  <% @author.poems.each do |poem| %>
    <%= link_to poem.title, poem_path(poem) %><br>
  <% end %>
<% end %>

<h4>Short stories</h4>

<% if @author.short_stories.count == 0 %>
  0 short stories
<% else %>
  <% @author.short_stories.each do |short_story| %>
    <%= link_to short_story.title, short_story_path(short_story) %><br>
  <% end %>
<% end %>

<h4>Tags</h4>

<%= render partial: 'tags/object_tags', locals: { target_object: @author, helper_path: "authors_path" } %>