config/routes.rb
Rails.application.routes.draw do

  root 'tags#index'

  resources :authors
  resources :poems
  resources :short_stories
  resources :tags

end

app/models/short_story.rb
# == Schema Information
#
# Table name: short_stories
#
#  id           :integer          not null, primary key
#  author_id    :integer
#  title        :string
#  description  :text
#  content      :text
#  published    :boolean
#  publish_date :datetime
#  created_at   :datetime
#  updated_at   :datetime
#

class ShortStory < ActiveRecord::Base
  include Tags

  belongs_to :author
  has_many   :tag_connections, class_name: "TagShortStory", dependent: :destroy
  has_many   :tags, through: :tag_connections, source: :tag

  validates :author_id, :title, :description, :content, presence: true
  validates :description, length: { maximum: 1000 }
  validates :content,     length: { maximum: 5000 }

  scope :by_tag_title, -> (tag_title) { joins(tag_connections: :tag).where(tags: {title: tag_title}) }

  after_save :update_tags, :update_publish_date

  TAG_TYPES = ['title', 'description', 'content']

  def publish!
    self.publish_date = DateTime.now
    self.save
  end

  def unpublish!
    self.publish_date = nil
    self.save
  end

  def update_tags
    TaggingService.new(self, TAG_TYPES).tag_content
  end

  def update_publish_date
    if published_changed? && published
      update_column(:publish_date, DateTime.now)
    end
  end

end

app/controllers/short_stories_controller.rb
class ShortStoriesController < ApplicationController

  before_action :set_short_story, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

  def index
    tag_title = params[:tag_title]
    @short_stories = ShortStory.all
    @short_stories = @short_stories.by_tag_title(tag_title) if tag_title.present?
  end

  def show
  end

  def new
    @short_story = ShortStory.new
  end

  def create
    @short_story = ShortStory.new(short_story_params)
    if @short_story.save
      redirect_to short_story_path(@short_story)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @short_story.update(short_story_params)
      redirect_to short_story_path(@short_story)
    else
      render :edit
    end
  end

  def destroy
    @short_story.destroy
    redirect_to short_stories_path
  end

  def publish
    @short_story.publish!
    redirect_to short_story_path(@short_story)
  end

  def unpublish
    @short_story.unpublish!
    redirect_to short_story_path(@short_story)
  end

  private

  def set_short_story
    @short_story = ShortStory.find(params[:id])
  end

  def short_story_params
    params.require(:short_story).permit(:id, :author_id, :published, :title, :description, :content)
  end

end

app/views/short_stories/_form.html.erb
<%= simple_form_for @short_story do |f| %>

  <h4>Author</h4>

  <div class="row">
    <div class="col-xs-12">
      <%= f.association :author, as: :select, label: false, include_blank: 'Select author' %>
    </div>
  </div>

  <h4>Title</h4>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :title, label: false %>
    </div>
  </div>

  <h4>Description</h4>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :description, label: false %>
    </div>
  </div>

  <h4>Content</h4>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :content, label: false %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
    <%= f.input :published %>
    </div>
  </div>
  <br><br>

  <div class="row">
    <div class="col-xs-12">
    <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/short_stories/edit.html.erb
<%= render partial: 'form' %>

app/views/short_stories/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= link_to 'New', new_short_story_path %>
  </div>
</div>

<table class="table table-hover">
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Description</th>
    <th>Content</th>
    <th>Published?</th>
    <th>Publish date</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @short_stories.each do |short_story| %>
    <tr>
      <td><%= short_story.author.present? ? link_to(short_story.author.name, author_path(short_story.author)) : 'Unknown author' %></td>
      <td><%= truncate(short_story.title, length: 35) %></td>
      <td><%= truncate(short_story.description, length: 65) %></td>
      <td><%= truncate(short_story.content, length: 65) %></td>
      <td><%= short_story.published? ? 'Yes' : 'No' %></td>
      <td><%= short_story.publish_date %></td>
      <td><%= link_to 'Show', short_story_path(short_story) %></td>
      <td><%= link_to 'Edit', edit_short_story_path(short_story) %></td>
      <td><%= link_to 'Delete', short_story_path(short_story), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/short_stories/new.html.erb
<%= render partial: 'form' %>

app/views/short_stories/show.html.erb
<h4>Author name</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @short_story.author.present? ? @short_story.author.name : 'Unknown author' %>
  </div>
</div>

<h4>Title</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @short_story.title %>
  </div>
</div>

<h4>Description</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @short_story.description %>
  </div>
</div>

<h4>Content</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @short_story.content %>
  </div>
</div>

<h4>Published?</h4>
<div class="row">
  <div class="col-xs-12">
    <%= @short_story.published? ? 'Yes' : 'No' %>
  </div>
</div>

<% if @short_story.published? %>
  <h4>Publish date</h4>
  <div class="row">
    <div class="col-xs-12">
      <%= @short_story.publish_date %>
    </div>
  </div>
<% end %>

<h4>Tags</h4>

<%= render partial: 'tags/object_tags', locals: { target_object: @short_story, helper_path: "short_stories_path" } %>