config/routes.rb
Rails.application.routes.draw do

  root 'tags#index'

  resources :authors
  resources :poems
  resources :short_stories
  resources :tags

end

app/models/concerns/tags.rb
module Tags
  extend ActiveSupport::Concern

  def all_tags
    tag_service.all
  end

  def grouped_tags_by_types
    tag_service.all_grouped_by_types
  end

  def tags_by_type(type)
    tag_service.by_type(type)
  end

  def tag_service
    @tag_service ||= TagService.new(self, TAG_TYPES)
  end

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime
#  updated_at :datetime
#

class Tag < ActiveRecord::Base
  has_many :tag_authors
  has_many :tag_poems
  has_many :tag_short_stories

  has_many :authors, through: :tag_authors, source: :author
  has_many :poems, through: :tag_poems, source: :poem
  has_many :short_story, through: :tag_short_stories, source: :short_story

  def self.grouped_authors_connections
    group_by_title("tag_authors")
  end

  def self.grouped_poems_connections
    group_by_title("tag_poems")
  end

  def self.grouped_short_stories_connections
    group_by_title("tag_short_stories")
  end

  def self.group_by_title(join_table)
    query = <<-SQL
      SELECT t.title, count(*) counter
      FROM tags t
      INNER JOIN #{join_table} jt
      ON t.id = jt.tag_id
      GROUP BY t.title
    SQL
    results = ActiveRecord::Base.connection.execute(query)
    tags_container = results.present? ? Hash[results.map { |row| [row["title"], row["counter"]] } ] : {}
    tags_container.sort_by { |key, value| -value }
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
  end

end

app/views/tags/_object_tags.html.erb
<div class="row">
  <div class="col-xs-8">
    <% target_object.tag_connections.ordered_by_weigth.each do |tag_connection| %>
      <%= link_to tag_connection.tag.title, send(helper_path, tag_title: tag_connection.tag.title) %><br>
    <% end %>
  </div>
</div>

app/views/tags/index.html.erb
<h3>Authors</h3>

<div class="row">
  <div class="col-xs-8">
    <% Tag.grouped_authors_connections.each do |title, counter| %>
      <%= link_to "#{title} (#{counter})", authors_path(tag_title: title) %><br>
    <% end %>
  </div>
</div>

<h3>Poems</h3>

<div class="row">
  <div class="col-xs-8">
    <% Tag.grouped_poems_connections.each do |title, counter| %>
      <%= link_to "#{title} (#{counter})", poems_path(tag_title: title) %><br>
    <% end %>
  </div>
</div>

<h3>Short stories</h3>

<div class="row">
  <div class="col-xs-8">
    <% Tag.grouped_short_stories_connections.each do |title, counter| %>
      <%= link_to "#{title} (#{counter})", short_stories_path(tag_title: title) %><br>
    <% end %>
  </div>
</div>